const assert = require('better-assert')
const uuid = require('uuid')
const knex = require('knex')({ client: 'pg' })
const {sql, _raw} = require('pg-extra')
const debug = require('debug')('app:db:index')